package DAL;
// Generated 28-dec-2014 21:43:21 by Hibernate Tools 4.3.1



/**
 * Receptentbl generated by hbm2java
 */
public class Receptentbl  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String omschrijving;
     private int wijnId;

    public Receptentbl() {
    }

    public Receptentbl(String naam, String omschrijving, int wijnId) {
       this.naam = naam;
       this.omschrijving = omschrijving;
       this.wijnId = wijnId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }
    public int getWijnId() {
        return this.wijnId;
    }
    
    public void setWijnId(int wijnId) {
        this.wijnId = wijnId;
    }




}


